# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-07 08:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hours', '0002_project_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='duration',
            field=models.DurationField(),
        ),
    ]
