# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-20 02:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hours', '0003_auto_20170107_1140'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255)),
                ('content_html', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('success', '\u0633\u0628\u0632'), ('info', '\u0622\u0628\u06cc'), ('warning', '\u0632\u0631\u062f')], max_length=20)),
                ('date', models.DateField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hours.Organization')),
            ],
        ),
    ]
