# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-20 02:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hours', '0004_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='content_html',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
