# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-06-27 02:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hours', '0005_auto_20180620_0717'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='category',
            field=models.CharField(choices=[('success', 'سبز'), ('info', 'آبی'), ('warning', 'زرد'), ('danger', 'قرمز')], max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='color',
            field=models.CharField(blank=True, choices=[('#ff9896', 'Red'), ('#f7b6d2', 'Pink'), ('#c5b0d5', 'Purple'), ('#68d8fd', 'Blue'), ('#9edae5', 'Cyan'), ('#98df8a', 'Green'), ('#dbdb8d', 'Olive'), ('#f5ff66', 'Yellow'), ('#c49c94', 'Brown'), ('#ffbb78', 'Orange')], max_length=10),
        ),
    ]
