# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-06-28 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hours', '0006_project_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='invitations',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='color',
            field=models.CharField(choices=[('#ff9896', 'Red'), ('#f7b6d2', 'Pink'), ('#c5b0d5', 'Purple'), ('#68d8fd', 'Blue'), ('#9edae5', 'Cyan'), ('#98df8a', 'Green'), ('#dbdb8d', 'Olive'), ('#f5ff66', 'Yellow'), ('#c49c94', 'Brown'), ('#ffbb78', 'Orange')], max_length=10),
        ),
    ]
