# Generated by Django 3.0.8 on 2020-08-23 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hours', '0008_holidays'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Holidays',
            new_name='Holiday',
        ),
    ]
