# Generated by Django 3.0.8 on 2020-08-25 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hours', '0009_auto_20200823_1712'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='holiday',
            options={'ordering': ['-date']},
        ),
    ]
