# Generated by Django 3.0.8 on 2020-08-25 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hours', '0010_auto_20200825_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='holiday',
            name='is_weekend',
            field=models.BooleanField(default=False),
        ),
    ]
