# Generated by Django 3.0.8 on 2020-08-25 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hours', '0011_holiday_is_weekend'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holiday',
            name='id',
        ),
        migrations.AlterField(
            model_name='holiday',
            name='date',
            field=models.DateField(primary_key=True, serialize=False),
        ),
    ]
