# Generated by Django 3.0.8 on 2020-08-26 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hours', '0012_auto_20200825_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='holiday',
            name='id',
            field=models.AutoField(auto_created=True, default=9999, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='holiday',
            name='date',
            field=models.DateField(null=True, unique=True),
        ),
    ]
