# Generated by Django 3.0.8 on 2020-08-27 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hours', '0013_auto_20200826_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holiday',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
