# Generated by Django 3.0.8 on 2020-08-27 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hours', '0014_auto_20200827_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holiday',
            name='date',
            field=models.DateField(null=True, unique=True),
        ),
    ]
